name: Visual
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn setup && yarn start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
          command-prefix: 'yarn run percy exec --'
